import type { CountryPurposeVisualSet } from './visuals';

export const NEXT_STUDY_PURPOSE_VISUALS = {
  'france:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1531686669028-c55493110d74?auto=format&fit=crop&w=2400&q=82',
      alt: 'パリのソルボンヌ地区にある大学建物の正面入口',
      width: 5724,
      height: 3816,
      location: 'Sorbonne, Paris, France',
      caption: 'パリのソルボンヌ地区にある大学建物。校舎の立地や街との距離まで確認すると、フランス留学後の毎日を具体的に描けます。',
      photographerName: 'Robin Benzrihem',
      photographerProfileUrl: 'https://unsplash.com/@robinoode',
      sourceUrl: 'https://unsplash.com/photos/universites-de-paris-building-nsHO6mtOsc4',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1650211233795-922f366885f9?auto=format&fit=crop&w=1800&q=82',
        alt: 'フランス国旗が掲げられたパリのソルボンヌ大学建物',
        width: 3927,
        height: 5891,
        location: "Sorbonne Université, Rue de l'École de Médecine, Paris, France",
        caption: 'パリのソルボンヌ大学。志望校を比べるときは、大学名だけでなく、課程・授業言語・キャンパスの場所も確認しましょう。',
        photographerName: 'Guillaume Didelet',
        photographerProfileUrl: 'https://unsplash.com/@mejlivg',
        sourceUrl: 'https://unsplash.com/photos/a-large-building-with-a-flag-on-top-of-it-AXvpNiPw7qY',
      },
      {
        src: 'https://images.unsplash.com/photo-1766847733864-9c93419a7cca?auto=format&fit=crop&w=1800&q=82',
        alt: 'パリ・モンマルトルのカフェや店が並ぶ通りを歩く人々',
        width: 3072,
        height: 5472,
        location: 'Montmartre, Paris, France',
        caption: 'モンマルトルの街角。授業外の買い物や食事、移動も含めたパリでの生活をイメージできる一場面です。',
        photographerName: 'Estera',
        photographerProfileUrl: 'https://unsplash.com/@esteranicoi',
        sourceUrl: 'https://unsplash.com/photos/people-walking-down-a-street-lined-with-cafes-and-shops-LENXVIT-gcE',
      },
    ],
  },
  'ireland:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1669380624544-4767be2c5928?auto=format&fit=crop&w=2400&q=82',
      alt: 'ダブリンのトリニティ・カレッジ構内を歩く学生や来訪者',
      width: 4434,
      height: 3108,
      location: 'Trinity College, Dublin, Ireland',
      caption: 'ダブリン中心部にあるトリニティ・カレッジ。大学と街が近い、アイルランド留学の日常を想像できる風景です。',
      photographerName: 'Help Stay',
      photographerProfileUrl: 'https://unsplash.com/@helpstay',
      sourceUrl: 'https://unsplash.com/photos/a-group-of-people-walking-around-a-large-building-FIuPkfo4LoU',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1509330336708-10b331f3ae6f?auto=format&fit=crop&w=1800&q=82',
        alt: 'トリニティ・カレッジ・ダブリンのロングルーム図書館を見学する人々',
        width: 5184,
        height: 3456,
        location: 'Trinity College Dublin, Ireland',
        caption: '歴史あるロングルーム図書館。大学の学習環境や、街の中で文化に触れられる暮らしを具体的に描けます。',
        photographerName: 'Hanna May',
        photographerProfileUrl: 'https://unsplash.com/@hanna405',
        sourceUrl: 'https://unsplash.com/photos/people-sitting-on-chair-inside-building-ORehLWGSZ4s',
      },
      {
        src: 'https://images.unsplash.com/photo-1706949486822-763586d354ce?auto=format&fit=crop&w=1800&q=82',
        alt: 'ダブリンの教会近くの芝生でくつろぐ人々',
        width: 3024,
        height: 4032,
        location: 'Dublin, Ireland',
        caption: 'ダブリンの芝生で過ごす人々。授業の外で友人と過ごす時間や、コンパクトな街の生活感が伝わる一場面です。',
        photographerName: 'Maria Angel',
        photographerProfileUrl: 'https://unsplash.com/@miss_startup',
        sourceUrl: 'https://unsplash.com/photos/a-group-of-people-sitting-on-top-of-a-lush-green-field-u5laBeru58o',
      },
    ],
  },
  'malta:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1669294841689-0ceb34ad40c1?auto=format&fit=crop&w=2400&q=82',
      alt: '木製バルコニーが並ぶマルタ・バレッタの坂道と海',
      width: 6000,
      height: 4000,
      location: 'Valletta, Malta',
      caption: 'バレッタの坂道と伝統的なバルコニー。石造りの街で学び、海の近くで暮らすマルタ留学の空気を感じられます。',
      photographerName: 'Michail Tsapas',
      photographerProfileUrl: 'https://unsplash.com/@mtsap',
      sourceUrl: 'https://unsplash.com/photos/valletta-street-with-traditional-wooden-balconies-KQyXCoy_8p0',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1736168527538-ca64f7105627?auto=format&fit=crop&w=1800&q=82',
        alt: 'バレッタの黄色い建物と屋外席で過ごす人々',
        width: 6000,
        height: 4000,
        location: 'Valletta, Malta',
        caption: 'バレッタのカフェがある街角。授業後の食事や交流を含め、歩いて楽しめる街の日常が伝わります。',
        photographerName: 'Kazuo ota',
        photographerProfileUrl: 'https://unsplash.com/@kazuo513',
        sourceUrl: 'https://unsplash.com/photos/a-yellow-building-with-people-sitting-outside-of-it-ZgVGKQPdMe0',
      },
      {
        src: 'https://images.unsplash.com/photo-1736531966731-13a77c33b61b?auto=format&fit=crop&w=1800&q=82',
        alt: 'バレッタの港を望むベンチで本を読む人',
        width: 3240,
        height: 5760,
        location: 'Valletta, Malta',
        caption: '港を望むバレッタのベンチ。海辺で過ごす休日や、落ち着いて読書をする生活の一場面です。',
        photographerName: 'Anja Lee Ming Becker',
        photographerProfileUrl: 'https://unsplash.com/@anjaleemingbecker',
        sourceUrl: 'https://unsplash.com/photos/a-woman-sitting-on-a-bench-next-to-a-body-of-water-T7YL2rtkGjQ',
      },
    ],
  },
  'philippines:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1619512673066-88a911c72026?auto=format&fit=crop&w=2400&q=82',
      alt: '緑に囲まれたマニラのファーイースタン大学キャンパス',
      width: 5184,
      height: 3456,
      location: 'Far Eastern University, Manila, Philippines',
      caption: 'マニラのファーイースタン大学。都市の中に緑があるキャンパスで学ぶ、フィリピン留学の一場面です。',
      photographerName: 'Richard Vance Cabusao',
      photographerProfileUrl: 'https://unsplash.com/@rxchi_cb',
      sourceUrl: 'https://unsplash.com/photos/white-concrete-building-near-green-trees-under-blue-sky-during-daytime-ZoQQyAIi1jg',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1727560783405-aca445d74d4c?auto=format&fit=crop&w=1800&q=82',
        alt: 'ケソン市にあるアテネオ・デ・マニラ大学の校名サイン',
        width: 5751,
        height: 3376,
        location: 'Ateneo de Manila University, Quezon City, Philippines',
        caption: 'アテネオ・デ・マニラ大学の入口。学校名だけで選ばず、認定・コース・立地を確認する大切さを想起させます。',
        photographerName: 'Bridget Adolfo',
        photographerProfileUrl: 'https://unsplash.com/@bridgetadolfo',
        sourceUrl: 'https://unsplash.com/photos/a-sign-on-the-side-of-a-building-that-says-atenco-de-manila-university-szt09VbsZ3M',
      },
      {
        src: 'https://images.unsplash.com/photo-1706477003009-5db295f58adf?auto=format&fit=crop&w=1800&q=82',
        alt: 'セブ市の小さな飲食店が並ぶ通りで過ごす人',
        width: 7008,
        height: 3942,
        location: 'Cebu City, Philippines',
        caption: 'セブ市の街角。教室外での食事や移動も含め、留学中の日常生活を具体的に想像できる景色です。',
        photographerName: 'XT7 Core',
        photographerProfileUrl: 'https://unsplash.com/@xt7core',
        sourceUrl: 'https://unsplash.com/photos/a-man-standing-in-front-of-a-coffee-shop-NcYcZHTXJsw',
      },
    ],
  },
} as const satisfies Readonly<Record<string, CountryPurposeVisualSet>>;
