import type { CountryPurposeVisualSet } from './visuals';

/**
 * Unsplashの写真ページで、作者・撮影地・元画像URLを確認した欧州6か国の素材。
 * 画像メタデータと直接画像のHTTP 200は2026年8月30日に確認済み。
 */
export const COUNTRY_PURPOSE_VISUALS_EUROPE = {
  'germany:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1495316364083-b5916626072e?auto=format&fit=crop&w=2400&q=82',
      alt: 'ドイツ・バイエルン州シュヴァンガウのノイシュヴァンシュタイン城と夕景',
      width: 5184,
      height: 3456,
      location: 'Neuschwanstein Castle, Schwangau, Germany',
      caption: 'バイエルン州シュヴァンガウのノイシュヴァンシュタイン城。ドイツ南部の山あいに広がる景観を伝える一枚です。',
      photographerName: 'Johannes Plenio',
      photographerProfileUrl: 'https://unsplash.com/@jplenio',
      sourceUrl: 'https://unsplash.com/photos/neuschwanstein-castle-germany-OwMTchwUTNw',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1606126210582-3a17753188b9?auto=format&fit=crop&w=1800&q=82',
        alt: 'ベルリン中心部で歩く人や自転車が行き交う街角',
        width: 6000,
        height: 4000,
        location: 'Berlin, Germany',
        caption: 'ベルリン中心部の街角。徒歩や自転車で移動する人が行き交う、市街地の日常風景です。',
        photographerName: 'Raja Sen',
        photographerProfileUrl: 'https://unsplash.com/@rajasen',
        sourceUrl: 'https://unsplash.com/photos/people-walking-on-sidewalk-near-beige-concrete-building-during-daytime-FrjdQhKSWb0',
      },
      {
        src: 'https://images.unsplash.com/photo-1695655555657-05786c55a019?auto=format&fit=crop&w=1800&q=82',
        alt: 'ベルリンの飲食店に並ぶ木製テーブルと椅子',
        width: 4480,
        height: 6720,
        location: 'Berlin, Germany',
        caption: 'ベルリンの飲食店内。街路に面した窓と木の家具から、食事や休憩をとる空間の雰囲気が伝わります。',
        photographerName: 'Kevin Woblick',
        photographerProfileUrl: 'https://unsplash.com/@kovah',
        sourceUrl: 'https://unsplash.com/photos/a-restaurant-with-a-wooden-table-and-chairs-IU0VWls6-v0',
      },
    ],
  },
  'france:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1531250552633-528fe896fdd4?auto=format&fit=crop&w=2400&q=82',
      alt: 'フランス・ノルマンディーの草原から望むモン・サン＝ミシェル',
      width: 3480,
      height: 2503,
      location: 'Mont Saint-Michel, France',
      caption: 'ノルマンディーの草原越しに望むモン・サン＝ミシェル。パリ以外にも地域ごとに異なる景観が広がります。',
      photographerName: 'dan wilding',
      photographerProfileUrl: 'https://unsplash.com/@danwilding',
      sourceUrl: 'https://unsplash.com/photos/mont-saint-michel-normandy-france-IQ1EuGwD-Lw',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1620664242907-0e4a8300ca54?auto=format&fit=crop&w=1800&q=82',
        alt: 'パリ・モンマルトルの石畳の坂道と歩く人々',
        width: 6000,
        height: 4000,
        location: 'Montmartre, Paris, France',
        caption: 'モンマルトルの坂道。勾配のある石畳と集合住宅が続く、パリの街並みです。',
        photographerName: 'Clément Dellandrea',
        photographerProfileUrl: 'https://unsplash.com/@clementdellandrea',
        sourceUrl: 'https://unsplash.com/photos/people-walking-on-street-between-buildings-during-daytime--qo0O0y3EUA',
      },
      {
        src: 'https://images.unsplash.com/photo-1686317508857-3b91999d6ec8?auto=format&fit=crop&w=1800&q=82',
        alt: 'フランス・パリの屋外カフェで過ごす人々',
        width: 5699,
        height: 3799,
        location: 'Paris, France',
        caption: 'パリのカフェテラス。屋外席で食事や会話を楽しむ人々と、街角の雰囲気が伝わります。',
        photographerName: 'Nico Knaack',
        photographerProfileUrl: 'https://unsplash.com/@xoxnk',
        sourceUrl: 'https://unsplash.com/photos/a-group-of-people-sitting-at-tables-outside-of-a-restaurant-vS-UmkMDkOc',
      },
    ],
  },
  'hungary:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1594224883490-43f520f73179?auto=format&fit=crop&w=2400&q=82',
      alt: 'ドナウ川と鎖橋を見渡すハンガリー・ブダペストの街並み',
      width: 6240,
      height: 3526,
      location: 'Budapest, Hungary',
      caption: 'ブダペストのドナウ川沿い。川を挟んでブダ地区とペスト地区が広がる、首都の地理をつかめる眺めです。',
      photographerName: 'Thomas Winkler',
      photographerProfileUrl: 'https://unsplash.com/@thomsonwinkler',
      sourceUrl: 'https://unsplash.com/photos/city-buildings-near-body-of-water-under-blue-and-white-sunny-cloudy-sky-during-daytime--Bbw2z6RzyM',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1650538935531-f16aead96ab6?auto=format&fit=crop&w=1800&q=82',
        alt: 'ブダペストの大通りを走る黄色いトラム',
        width: 5184,
        height: 3456,
        location: 'Budapest, Hungary',
        caption: 'ブダペストの街を走るトラム。線路と車道、自転車レーンが並ぶ市街地の移動環境です。',
        photographerName: 'Andrea Huls Pareja',
        photographerProfileUrl: 'https://unsplash.com/@andreahuls',
        sourceUrl: 'https://unsplash.com/photos/a-yellow-trolley-is-going-down-the-street-77g_zUcjLYs',
      },
      {
        src: 'https://images.unsplash.com/photo-1750702875797-d339804caff2?auto=format&fit=crop&w=1800&q=82',
        alt: 'ブダペストのニューヨーク・カフェで食事をする人々と装飾的な店内',
        width: 5654,
        height: 4523,
        location: 'New York Café, Budapest, Hungary',
        caption: 'ブダペストのNew York Café。装飾豊かな店内と多くの利用客が見える、街の飲食文化の一場面です。',
        photographerName: 'Narbeh Arakil',
        photographerProfileUrl: 'https://unsplash.com/@narbehaj',
        sourceUrl: 'https://unsplash.com/photos/people-dine-in-a-lavish-and-ornate-restaurant-XOj6uOWt5z0',
      },
    ],
  },
  'italy:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1518098268026-4e89f1a2cd8e?auto=format&fit=crop&w=2400&q=82',
      alt: 'イタリア・トスカーナの丘陵を縫う糸杉並木の道と夕焼け',
      width: 4828,
      height: 3619,
      location: "San Quirico d'Orcia, Italy",
      caption: 'サン・クイーリコ・ドルチャ周辺の丘陵。都市と地方で大きく異なるイタリアの景観を伝える一枚です。',
      photographerName: 'Luca Micheli',
      photographerProfileUrl: 'https://unsplash.com/@lucamicheli',
      sourceUrl: 'https://unsplash.com/photos/winding-road-in-tuscany-hills-r9RW20TrQ0Y',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1711719873824-5651462f64ed?auto=format&fit=crop&w=1800&q=82',
        alt: 'イタリア・トリノの石畳の通りに駐車する小型車と歴史的建物',
        width: 6000,
        height: 4000,
        location: 'Turin, Italy',
        caption: 'トリノの石畳の通り。歴史的な建物と小型車が並ぶ、市街地の日常風景です。',
        photographerName: 'Laura V.',
        photographerProfileUrl: 'https://unsplash.com/@lauravsn_',
        sourceUrl: 'https://unsplash.com/photos/a-small-car-is-parked-on-a-cobblestone-street-gSHh1bgwakk',
      },
      {
        src: 'https://images.unsplash.com/photo-1595972025118-1e1dc9cc2bd0?auto=format&fit=crop&w=1800&q=82',
        alt: 'イタリア・ラヴェッロの屋外席で食事を楽しむ人々',
        width: 2940,
        height: 1972,
        location: 'Ravello, SA, Italy',
        caption: '南イタリア・ラヴェッロの屋外レストラン。建物の表情と人が集まる昼の街角を写しています。',
        photographerName: 'Sterling Lanier',
        photographerProfileUrl: 'https://unsplash.com/@sterlinglanier',
        sourceUrl: 'https://unsplash.com/photos/people-sitting-on-chairs-near-brown-concrete-building-during-daytime-Lg4b4clKYIg',
      },
    ],
  },
  'latvia:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1563359474-654203f41b55?auto=format&fit=crop&w=2400&q=82',
      alt: 'ラトビア・サウルクラスティのバルト海沿岸を走る道路と森林',
      width: 3502,
      height: 2625,
      location: 'Saulkrasti, Latvia',
      caption: 'サウルクラスティの海岸線。バルト海、砂浜、森林が並ぶラトビアの沿岸景観です。',
      photographerName: 'Gints Gailis',
      photographerProfileUrl: 'https://unsplash.com/@gintsgailis',
      sourceUrl: 'https://unsplash.com/photos/aerial-photograph-of-road-beside-sea-PtwXH7H6itY',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1646929761543-b6b269ab66c6?auto=format&fit=crop&w=1800&q=82',
        alt: 'ラトビア・リガの市街地を歩く人々と路面電車の線路',
        width: 3464,
        height: 2309,
        location: 'Riga, Latvia',
        caption: 'リガ中心部の通り。歩行者、自転車、路面電車の線路が見える日中の街並みです。',
        photographerName: 'Krišjānis Kazaks',
        photographerProfileUrl: 'https://unsplash.com/@kazaks',
        sourceUrl: 'https://unsplash.com/photos/a-group-of-people-walking-down-a-street-next-to-tall-buildings-LQtneyqXits',
      },
      {
        src: 'https://images.unsplash.com/photo-1785063066809-2197836dcb8f?auto=format&fit=crop&w=1800&q=82',
        alt: 'ラトビア・リガのカフェに差し込む日差しと木製のテーブル',
        width: 3918,
        height: 5888,
        location: 'Grēcinieku iela, Riga, Latvia',
        caption: 'リガ中心部のカフェ。本棚や植物、木の家具が並ぶ、日差しの入る店内です。',
        photographerName: 'Kristīne Kozaka',
        photographerProfileUrl: 'https://unsplash.com/@christina_kozak',
        sourceUrl: 'https://unsplash.com/photos/cozy-cafe-interior-with-tables-chairs-books-and-sunlight-hCX6fe9YCiM',
      },
    ],
  },
  'lithuania:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1748447647359-ab108b0acaf3?auto=format&fit=crop&w=2400&q=82',
      alt: 'リトアニア・トラカイの湖上に建つトラカイ島城',
      width: 8368,
      height: 5230,
      location: 'Trakai Island Castle, Trakai, Lithuania',
      caption: 'トラカイの湖上に建つトラカイ島城。湖と森林に囲まれたリトアニアの景観を伝える一枚です。',
      photographerName: 'Hans-Joachim Kaiser',
      photographerProfileUrl: 'https://unsplash.com/@zesa',
      sourceUrl: 'https://unsplash.com/photos/a-castle-is-situated-on-a-serene-lake-YKCdDdwMCag',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1614070027640-1910da15267a?auto=format&fit=crop&w=1800&q=82',
        alt: 'リトアニア・ヴィリニュス中心部の石畳の通りを歩く人々',
        width: 4000,
        height: 6000,
        location: 'Vilnius, Lithuania',
        caption: 'ヴィリニュス中心部の街角。飲食店のテラスと石畳の通りを歩く人々が見えます。',
        photographerName: 'Jonas Abukauskas',
        photographerProfileUrl: 'https://unsplash.com/@k_onas',
        sourceUrl: 'https://unsplash.com/photos/people-walking-on-street-near-white-concrete-building-during-daytime-ltM24UXmCjo',
      },
      {
        src: 'https://images.unsplash.com/photo-1656329379711-15fdc3e02c8b?auto=format&fit=crop&w=1800&q=82',
        alt: 'ヴィリニュスの屋外カフェで過ごす人々と植物で飾られた壁',
        width: 4160,
        height: 6240,
        location: 'Vilnius, Lithuania',
        caption: 'ヴィリニュスの屋外席。大きな植栽とテーブル席から、暖かい時期の街の雰囲気が伝わります。',
        photographerName: 'Aleksey Cherenkevich',
        photographerProfileUrl: 'https://unsplash.com/@cherenkevich',
        sourceUrl: 'https://unsplash.com/photos/a-group-of-people-sitting-outside-a-restaurant-iO-JrpOXFD8',
      },
    ],
  },
} as const satisfies Readonly<Record<string, CountryPurposeVisualSet>>;
