import type { CountryPurposeVisualSet } from './visuals';

/**
 * COUNTRY_PURPOSE_VISUALS へマージするための英語圏7ページ分の候補。
 * 2026-08-30 に Unsplash の各写真ページ / NAPI メタデータと直接画像を照合済み。
 * hero は w=2400、inline は w=1800。全21画像で HTTP 200 / image/jpeg を確認済み。
 */
export const ENGLISH_MARKET_PURPOSE_VISUALS = {
  'australia:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1446768188400-0cf64a86da7e?auto=format&fit=crop&w=2400&q=82',
      alt: 'オーストラリア・ケープオトウェイの岬に立つ灯台と海岸線',
      width: 4056,
      height: 1679,
      location: 'Cape Otway Lightstation, Cape Otway, Australia',
      caption: 'ビクトリア州ケープオトウェイの灯台と海岸線。国土の広さと、都市から足を延ばした先の自然をイメージできる風景です。',
      photographerName: 'Joshua Hibbert',
      photographerProfileUrl: 'https://unsplash.com/@joshnh',
      sourceUrl: 'https://unsplash.com/photos/white-lighthouse-on-the-edge-of-cliff-GJPteyGnk5k',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1514395629347-41e19e338c6a?auto=format&fit=crop&w=1800&q=82',
        alt: 'メルボルンのフリンダース・ストリートを走る黄色いトラムと横断歩道を渡る人々',
        width: 6000,
        height: 4000,
        location: 'Flinders Street, Melbourne, Australia',
        caption: 'メルボルン中心部のフリンダース・ストリート。トラムと徒歩が交わる、日々の移動をイメージできる街角です。',
        photographerName: 'XY YEW',
        photographerProfileUrl: 'https://unsplash.com/@blurblock07',
        sourceUrl: 'https://unsplash.com/photos/people-crossing-road-near-yellow-train-PCbpcMAY_ew',
      },
      {
        src: 'https://images.unsplash.com/photo-1530276371031-2511efff9d5a?auto=format&fit=crop&w=1800&q=82',
        alt: 'シドニーのジョージ・ストリートで路面電車の軌道沿いを走る自転車',
        width: 3385,
        height: 5077,
        location: 'George Street, Sydney, Australia',
        caption: 'シドニー中心部のジョージ・ストリート。歩行者空間、路面電車、自転車が共存する都市の一場面です。',
        photographerName: 'Laura Cros',
        photographerProfileUrl: 'https://unsplash.com/@locreaphoto',
        sourceUrl: 'https://unsplash.com/photos/cyclist-on-pedestrian-street-in-sydney-KtJy7cZV5OQ',
      },
    ],
  },

  'canada:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=2400&q=82',
      alt: 'カナダ・クルアニ国立公園の雪山と針葉樹林',
      width: 5760,
      height: 3840,
      location: 'Kluane National Park and Reserve of Canada, Canada',
      caption: 'ユーコン準州のクルアニ国立公園。都市での仕事や暮らしとともに、カナダの広大な自然も具体的に思い描ける風景です。',
      photographerName: 'Kalen Emsley',
      photographerProfileUrl: 'https://unsplash.com/@kalenemsley',
      sourceUrl: 'https://unsplash.com/photos/snow-capped-mountains-with-valley-and-forest-Bkci_8qcdvQ',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1514924013411-cbf25faa35bb?auto=format&fit=crop&w=1800&q=82',
        alt: '雪の日のトロントに立つフラットアイアンビルと高層建築',
        width: 3301,
        height: 4913,
        location: 'Toronto, Canada',
        caption: '冬のトロント中心部。寒さや雪を前提に、通勤・住居・衣類を考える必要がある現地生活を想像できる景色です。',
        photographerName: 'Dawson Lovell',
        photographerProfileUrl: 'https://unsplash.com/@dawsonlovell',
        sourceUrl: 'https://unsplash.com/photos/flatiron-building-in-toronto-W_MUqtuHwyY',
      },
      {
        src: 'https://images.unsplash.com/photo-1677791267383-df800fe824f0?auto=format&fit=crop&w=1800&q=82',
        alt: 'モントリオールの市街地を歩く人々と高層建築',
        width: 6000,
        height: 4000,
        location: 'Montreal, QC, Canada',
        caption: 'モントリオールの街路。歩いて移動する人々や建物の距離感から、日常の都市生活をイメージできます。',
        photographerName: 'Asael Peña',
        photographerProfileUrl: 'https://unsplash.com/@asaelamaury',
        sourceUrl: 'https://unsplash.com/photos/a-group-of-people-walking-down-a-street-next-to-tall-buildings-J6VmHgtFM4k',
      },
    ],
  },

  'canada:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1753246786395-b2eb9dd447fd?auto=format&fit=crop&w=2400&q=82',
      alt: 'バンクーバーにあるブリティッシュコロンビア大学のキャンパス建築',
      width: 6016,
      height: 4016,
      location: 'The University of British Columbia, University Blvd, Vancouver, BC, Canada',
      caption: 'バンクーバーのブリティッシュコロンビア大学キャンパス。学校選びでは、授業だけでなく周辺環境や通学生活も確認したいポイントです。',
      photographerName: 'Chenhsi Duan',
      photographerProfileUrl: 'https://unsplash.com/@_royat',
      sourceUrl: 'https://unsplash.com/photos/buildings-with-a-clear-blue-sky-in-the-background-GiMKW9JcGOs',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1642130935796-1409d7e075dd?auto=format&fit=crop&w=1800&q=82',
        alt: 'アルバータ大学の書架が並ぶ図書館',
        width: 3024,
        height: 4032,
        location: 'University of Alberta, Canada',
        caption: 'アルバータ大学の図書館。授業時間だけでなく、自習や資料調査を行う学習環境も留学生活の大切な一部です。',
        photographerName: 'Clementine',
        photographerProfileUrl: 'https://unsplash.com/@s8n3d8gb2js0a3w4',
        sourceUrl: 'https://unsplash.com/photos/a-row-of-bookshelves-in-a-library-filled-with-lots-of-books-JNJEGrP9raA',
      },
      {
        src: 'https://images.unsplash.com/photo-1618255630366-f402c45736f6?auto=format&fit=crop&w=1800&q=82',
        alt: 'トロントの大学周辺にある歴史的な校舎と緑',
        width: 3662,
        height: 2744,
        location: 'University, Toronto, ON, Canada',
        caption: 'トロントの大学周辺にある歴史的な建物。大都市型の留学では、キャンパスと街が近い生活も選択肢になります。',
        photographerName: 'Dora Dalberto',
        photographerProfileUrl: 'https://unsplash.com/@doradalberto',
        sourceUrl: 'https://unsplash.com/photos/brown-and-gray-concrete-building-near-green-trees-under-blue-sky-during-daytime-ORzZtY2i50k',
      },
    ],
  },

  'united-kingdom:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=2400&q=82',
      alt: 'ザ・シャードから望むロンドンの市街地とテムズ川',
      width: 4896,
      height: 3264,
      location: 'The View from The Shard, London, United Kingdom',
      caption: 'ザ・シャードから見たロンドンの市街地。広い生活圏と多様なエリアを持つ都市で暮らすイメージをつかめます。',
      photographerName: 'Benjamin Davies',
      photographerProfileUrl: 'https://unsplash.com/@bendavisual',
      sourceUrl: 'https://unsplash.com/photos/aerial-photography-of-london-skyline-during-daytime-Oja2ty_9ZLM',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1691746210635-6144287c2808?auto=format&fit=crop&w=1800&q=82',
        alt: 'ロンドンの市街地を走る赤と白のバス',
        width: 2228,
        height: 3961,
        location: 'London, United Kingdom',
        caption: 'ロンドンの市街地とバス。住む場所を選ぶ際は、家賃だけでなく職場までの交通や所要時間も重要になります。',
        photographerName: 'Alireza Hamid',
        photographerProfileUrl: 'https://unsplash.com/@alihd',
        sourceUrl: 'https://unsplash.com/photos/a-red-and-white-bus-driving-down-a-street-next-to-tall-buildings-VSq-PCmjHWQ',
      },
      {
        src: 'https://images.unsplash.com/photo-1722048366911-3012225ff0c8?auto=format&fit=crop&w=1800&q=82',
        alt: 'ロンドン中心部の飲食店の屋外席で過ごす人々',
        width: 5152,
        height: 6864,
        location: 'The Spice of Life, London, United Kingdom',
        caption: 'ロンドン中心部の飲食店にある屋外席。仕事や移動だけでなく、人が集まる街の日常も感じられる一場面です。',
        photographerName: 'Saheem c',
        photographerProfileUrl: 'https://unsplash.com/@saheemc',
        sourceUrl: 'https://unsplash.com/photos/a-group-of-people-sitting-at-tables-outside-of-a-restaurant-6HUfzrRU11k',
      },
    ],
  },

  'united-kingdom:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1612563958093-2c3bcfbd8760?auto=format&fit=crop&w=2400&q=82',
      alt: 'オックスフォード大学のラドクリフ・カメラと歴史的な学寮の建物',
      width: 4675,
      height: 2687,
      location: 'Oxford, United Kingdom',
      caption: 'オックスフォード大学のラドクリフ・カメラ。イギリス留学では、コース内容だけでなく学習環境や都市の雰囲気も比較材料になります。',
      photographerName: 'Ben Seymour',
      photographerProfileUrl: 'https://unsplash.com/@benseymour',
      sourceUrl: 'https://unsplash.com/photos/radcliffe-camera-in-oxford-nqBUTBsDQNM',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1667082797547-ad78286801e0?auto=format&fit=crop&w=1800&q=82',
        alt: 'オックスフォードの大学街に並ぶ自転車と学生の日常風景',
        width: 3403,
        height: 5104,
        location: 'Oxford, United Kingdom',
        caption: 'オックスフォードの大学街に並ぶ自転車。通学手段や街の規模まで考えると、実際の留学生活をより具体的に想像できます。',
        photographerName: 'BEN ELLIOTT',
        photographerProfileUrl: 'https://unsplash.com/@benjaminelliott',
        sourceUrl: 'https://unsplash.com/photos/a-large-group-of-bicycles-parked-on-the-side-of-a-street-kj2cYaCCEF0',
      },
      {
        src: 'https://images.unsplash.com/photo-1759734353125-6913ba6c6804?auto=format&fit=crop&w=1800&q=82',
        alt: 'マンチェスター大学の塔がある石造校舎とキャンパス',
        width: 8192,
        height: 3827,
        location: 'The University of Manchester, Manchester, United Kingdom',
        caption: 'マンチェスター大学のキャンパス。ロンドン以外の大学都市も、学費・住居・生活費と学びたい分野を合わせて比べる候補です。',
        photographerName: 'Michael D Beckwith',
        photographerProfileUrl: 'https://unsplash.com/@mdbeckwith',
        sourceUrl: 'https://unsplash.com/photos/large-stone-building-with-a-tall-tower-and-red-roof-8RKvvS0dUIM',
      },
    ],
  },

  'australia:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1646641677623-269c66f1c41f?auto=format&fit=crop&w=2400&q=82',
      alt: 'シドニー大学の歴史的な校舎と芝生のキャンパス',
      width: 3003,
      height: 2252,
      location: 'The University of Sydney, Sydney, Australia',
      caption: 'シドニー大学のキャンパス。学校選びでは、コースだけでなく通学環境や街との距離も比べたいポイントです。',
      photographerName: 'Datingscout',
      photographerProfileUrl: 'https://unsplash.com/@datingscout',
      sourceUrl: 'https://unsplash.com/photos/a-large-building-with-a-long-walkway-in-front-of-it-AuC9RiKvClA',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1720525200240-17cd4ffd127f?auto=format&fit=crop&w=1800&q=82',
        alt: 'ニューサウスウェールズ大学の中庭で過ごす学生たち',
        width: 4000,
        height: 3000,
        location: 'UNSW Sydney, Sydney, Australia',
        caption: 'ニューサウスウェールズ大学の中庭。授業以外の時間を過ごす場所や、学生同士が交流する環境も留学生活の一部です。',
        photographerName: 'Dominic Kurniawan Suryaputra',
        photographerProfileUrl: 'https://unsplash.com/@d_ks11',
        sourceUrl: 'https://unsplash.com/photos/a-group-of-people-sitting-on-top-of-a-lush-green-field-tputvRf4bjA',
      },
      {
        src: 'https://images.unsplash.com/photo-1721702754494-fdd7189f946c?auto=format&fit=crop&w=1800&q=82',
        alt: 'ニューサウスウェールズ州立図書館の閲覧室で学ぶ人々',
        width: 4240,
        height: 2832,
        location: 'State Library of New South Wales, Sydney, Australia',
        caption: 'シドニーのニューサウスウェールズ州立図書館。キャンパス外も含め、自習や資料調査に使える学習環境を確認すると生活を具体化できます。',
        photographerName: 'Dominic Kurniawan Suryaputra',
        photographerProfileUrl: 'https://unsplash.com/@d_ks11',
        sourceUrl: 'https://unsplash.com/photos/a-large-library-filled-with-lots-of-books-r0U2y0HhdGE',
      },
    ],
  },

  'new-zealand:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1597655601841-214a4cfe8b2c?auto=format&fit=crop&w=2400&q=82',
      alt: 'ニュージーランド・タラナキ山とプアカイ・ターンズの水面',
      width: 4747,
      height: 4000,
      location: 'Mount Taranaki / Mount Egmont, Taranaki, New Zealand',
      caption: 'プアカイ・ターンズの水面に映るタラナキ山。都市と自然の距離感をイメージできる、ニュージーランドらしい風景です。',
      photographerName: 'Sophie Turner',
      photographerProfileUrl: 'https://unsplash.com/@sophie_turner',
      sourceUrl: 'https://unsplash.com/photos/mount-taranaki-reflection-in-pouaki-tarns-LZVmvKlchM0',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1537528013590-d81d3c8a04a4?auto=format&fit=crop&w=1800&q=82',
        alt: 'オークランド中心部の横断歩道を歩く人々と市街地',
        width: 4928,
        height: 2914,
        location: 'Auckland, New Zealand',
        caption: 'オークランド中心部の街路。人の流れや車、建物の距離感から、現地での通勤や買い物を想像できます。',
        photographerName: 'Tanay Vora',
        photographerProfileUrl: 'https://unsplash.com/@gridsandlayers',
        sourceUrl: 'https://unsplash.com/photos/people-walking-on-road-and-cars-on-gray-pave-road-near-buildings-hiE07f-Es1s',
      },
      {
        src: 'https://images.unsplash.com/photo-1547314283-befb6cc5cf29?auto=format&fit=crop&w=1800&q=82',
        alt: 'クイーンズタウンの湖畔の街並みと山々',
        width: 3840,
        height: 2160,
        location: 'Queenstown Hill, Queenstown, New Zealand',
        caption: 'クイーンズタウンの湖畔と山に囲まれた街並み。大都市とは異なる地域で暮らす場合の環境を思い描けます。',
        photographerName: 'Ömer Faruk Bekdemir',
        photographerProfileUrl: 'https://unsplash.com/@ofbekdemir',
        sourceUrl: 'https://unsplash.com/photos/buildings-near-body-of-water-and-mountains-under-clear-blue-sky-and-white-clouds-at-daytime-5BuxuWIJF1Q',
      },
    ],
  },

  'new-zealand:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1590999913779-47b338684662?auto=format&fit=crop&w=2400&q=82',
      alt: 'ビクトリア大学ウェリントン校ケルバーンキャンパスから望む市街地と港',
      width: 6132,
      height: 2946,
      location: 'Victoria University of Wellington, Wellington, New Zealand',
      caption: 'ビクトリア大学ウェリントン校のケルバーンキャンパスから見た市街地。通学経路や住居の場所まで含めて都市を選ぶ手がかりになります。',
      photographerName: 'Sanjeev Bothra',
      photographerProfileUrl: 'https://unsplash.com/@sanjeevbothra',
      sourceUrl: 'https://unsplash.com/photos/city-with-high-rise-buildings-under-blue-sky-during-daytime-2u9XFRTkC7o',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1702736310801-d89342db8435?auto=format&fit=crop&w=1800&q=82',
        alt: 'ダニーデンにあるオタゴ大学の時計塔と石造校舎',
        width: 3352,
        height: 5028,
        location: 'University of Otago, Dunedin, New Zealand',
        caption: 'ダニーデンのオタゴ大学時計塔。大都市だけでなく大学都市も、専攻・住居・生活費を合わせて比較する候補です。',
        photographerName: 'K8',
        photographerProfileUrl: 'https://unsplash.com/@_k8_',
        sourceUrl: 'https://unsplash.com/photos/a-large-building-with-a-clock-on-the-front-of-it-Syft77Kc4zI',
      },
      {
        src: 'https://images.unsplash.com/photo-1589634752793-aabd114351ed?auto=format&fit=crop&w=1800&q=82',
        alt: 'ラグランの海を望む芝生で友人同士が集う生活風景',
        width: 5472,
        height: 3648,
        location: 'Raglan, New Zealand',
        caption: '北島ラグランで人々が集う夕方の風景。学校の外で過ごす時間や、休日の移動も現地生活を考える材料になります。',
        photographerName: 'Mike Swigunski',
        photographerProfileUrl: 'https://unsplash.com/@mike_swigunski',
        sourceUrl: 'https://unsplash.com/photos/people-sitting-on-grass-field-during-daytime-jQbW2K42m0o',
      },
    ],
  },

  'united-states:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1736451497343-6053161bcdde?auto=format&fit=crop&w=2400&q=82',
      alt: 'ハーバード大学の赤レンガ校舎と芝生',
      width: 5728,
      height: 3819,
      location: 'Harvard University, Cambridge, MA, USA',
      caption: 'マサチューセッツ州ケンブリッジのハーバード大学。米国留学では、学校ごとに異なるキャンパス環境も比較材料になります。',
      photographerName: 'Mikheil Kuzmidi',
      photographerProfileUrl: 'https://unsplash.com/@mikkuz',
      sourceUrl: 'https://unsplash.com/photos/a-large-brick-building-with-a-grassy-area-in-front-of-it-0B7beai9DRY',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1741637335289-c99652d3155f?auto=format&fit=crop&w=1800&q=82',
        alt: 'ワシントン大学の学生会館前を歩く人々',
        width: 6000,
        height: 4000,
        location: 'Husky Union Building, University of Washington, Seattle, WA, USA',
        caption: 'シアトルのワシントン大学で、学生会館前を人々が行き交う様子。授業外の時間を過ごす共用施設も学校生活の一部です。',
        photographerName: 'Zoshua Colah',
        photographerProfileUrl: 'https://unsplash.com/@zoshuacolah',
        sourceUrl: 'https://unsplash.com/photos/students-walk-by-a-campus-building-under-a-tree-kaZHJj-DhC4',
      },
      {
        src: 'https://images.unsplash.com/photo-1610558751153-154582773d89?auto=format&fit=crop&w=1800&q=82',
        alt: '南カリフォルニア大学の緑に囲まれたキャンパス建築',
        width: 4000,
        height: 2250,
        location: 'University of Southern California, Los Angeles, CA, USA',
        caption: 'ロサンゼルスの南カリフォルニア大学。地域や気候によっても、通学環境とキャンパスの雰囲気は変わります。',
        photographerName: 'Greg Campbell',
        photographerProfileUrl: 'https://unsplash.com/@greg_campbell400',
        sourceUrl: 'https://unsplash.com/photos/green-trees-near-city-buildings-during-daytime-XLtXWLL95r4',
      },
    ],
  },

  'ireland:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1602354817989-b9664561ae84?auto=format&fit=crop&w=2400&q=82',
      alt: 'アイルランド・クレア県のモハーの断崖と大西洋',
      width: 3719,
      height: 2281,
      location: 'Cliffs of Moher, Lislorkan North, County Clare, Ireland',
      caption: 'クレア県のモハーの断崖と大西洋。都市での暮らしとは異なる雄大な自然も、この国の環境を知る手がかりです。',
      photographerName: 'Sean Kuriyan',
      photographerProfileUrl: 'https://unsplash.com/@sean189',
      sourceUrl: 'https://unsplash.com/photos/green-grass-covered-mountain-under-cloudy-sky-during-daytime-sKm0RZjOgIE',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1549918864-48ac978761a4?auto=format&fit=crop&w=1800&q=82',
        alt: 'ダブリンのアン・ストリートを歩く人々と教会の塔',
        width: 6183,
        height: 4122,
        location: 'Anne Street, Dublin, Ireland',
        caption: 'ダブリン中心部のアン・ストリート。徒歩で街を移動する日常や、市街地の建物の距離感をイメージできます。',
        photographerName: 'Gregory DALLEAU',
        photographerProfileUrl: 'https://unsplash.com/@gregda',
        sourceUrl: 'https://unsplash.com/photos/people-walking-on-street-heading-towards-church-KT4dOfvtZSg',
      },
      {
        src: 'https://images.unsplash.com/photo-1518005068251-37900150dfca?auto=format&fit=crop&w=1800&q=82',
        alt: 'ダブリンのテンプルバー地区に並ぶ色彩豊かな建物',
        width: 3008,
        height: 2000,
        location: 'Temple Bar, Dublin, Ireland',
        caption: 'ダブリンのテンプルバー地区に並ぶ建物。飲食店や文化施設が集まる中心街の雰囲気を伝える街並みです。',
        photographerName: 'Diogo Palhais',
        photographerProfileUrl: 'https://unsplash.com/@diogopalhais',
        sourceUrl: 'https://unsplash.com/photos/brown-and-white-concrete-houses-tnzzr8HpLhs',
      },
    ],
  },
} as const satisfies Readonly<Record<string, CountryPurposeVisualSet>>;
