import type { CountryPurposeVisualSet } from './visuals';

export const ASIA_SOUTH_AMERICA_COUNTRY_PURPOSE_VISUALS = {
  'south-korea:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1546874177-9e664107314e?auto=format&fit=crop&w=2400&q=82',
      alt: '夕暮れのソウル市街と南山ソウルタワー',
      width: 6016,
      height: 4016,
      location: 'Seoul, South Korea',
      caption: '南山ソウルタワーを望む夕暮れのソウル。高層ビルと山が近接する都市の広がりを感じられます。',
      photographerName: 'Yohan Cho',
      photographerProfileUrl: 'https://unsplash.com/@yohoney',
      sourceUrl: 'https://unsplash.com/photos/lighted-city-skyline-at-night-Mwvhyd22Lyw',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?auto=format&fit=crop&w=1800&q=82',
        alt: '飲食店の看板が並ぶ夜のソウルの通り',
        width: 1955,
        height: 3033,
        location: 'Seoul, South Korea',
        caption: '飲食店やカラオケ店の看板が並ぶ夜のソウル。帰宅後や休日に街へ出る日常をイメージできる一場面です。',
        photographerName: 'Stéphan Valentin',
        photographerProfileUrl: 'https://unsplash.com/@valentinsteph',
        sourceUrl: 'https://unsplash.com/photos/neon-street-in-seoul-at-night-wepDTOWs4d0',
      },
      {
        src: 'https://images.unsplash.com/photo-1603852452515-2dc92bd9c6f1?auto=format&fit=crop&w=1800&q=82',
        alt: '池と山を背景にしたソウルの伝統建築',
        width: 3647,
        height: 4559,
        location: 'Seoul, South Korea',
        caption: '池と山を背景にしたソウルの伝統建築。にぎやかな市街地とは異なる、落ち着いた休日の過ごし方も想像できます。',
        photographerName: 'jet dela cruz',
        photographerProfileUrl: 'https://unsplash.com/@jetjetdelacruz',
        sourceUrl: 'https://unsplash.com/photos/brown-and-white-house-near-green-trees-and-lake-during-daytime-Gf6puSx3h6Y',
      },
    ],
  },

  'south-korea:study-abroad': {
    hero: {
      src: 'https://images.unsplash.com/photo-1777823627849-8fc134d3a826?auto=format&fit=crop&w=2400&q=82',
      alt: 'ソウルの中央大学キャンパスにある時計塔付きの図書館',
      width: 5184,
      height: 3456,
      location: 'Chung-Ang University, Seoul, South Korea',
      caption: 'ソウルの中央大学キャンパスにある図書館。学校選びでは、授業だけでなく学習設備や通学環境も比べたいポイントです。',
      photographerName: 'TAO GARY',
      photographerProfileUrl: 'https://unsplash.com/@gary_t',
      sourceUrl: 'https://unsplash.com/photos/a-modern-building-with-a-clock-tower-and-trees-97tcm3wlbNY',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1768578987465-ed41517c93e3?auto=format&fit=crop&w=1800&q=82',
        alt: '韓国・水原の大学街を歩く学生たちとキャンパスの門',
        width: 2423,
        height: 3240,
        location: 'Suwon-si, Gyeonggi-do, South Korea',
        caption: '水原の大学街を歩く学生たち。キャンパス内だけでなく、住居や交通を含む周辺環境も留学生活の一部です。',
        photographerName: 'YMA',
        photographerProfileUrl: 'https://unsplash.com/@anhsy',
        sourceUrl: 'https://unsplash.com/photos/people-walking-on-a-city-street-under-an-archway-PIZMiShfwOE',
      },
      {
        src: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?auto=format&fit=crop&w=1800&q=82',
        alt: 'ソウル市立大学の階段状に机が並ぶ大学講義室',
        width: 4240,
        height: 2832,
        location: 'University of Seoul, Seoul, South Korea',
        caption: 'ソウル市立大学の講義室。授業形式、クラス規模、学習支援まで確認すると、入学後の学び方を具体的に想像できます。',
        photographerName: 'Changbok Ko',
        photographerProfileUrl: 'https://unsplash.com/@kochangbok',
        sourceUrl: 'https://unsplash.com/photos/empty-university-lecture-hall-desks-F8t2VGnI47I',
      },
    ],
  },

  'taiwan:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1572715381359-002b1eabd56b?auto=format&fit=crop&w=2400&q=82',
      alt: '象山から望む台北101と台北市街',
      width: 6000,
      height: 4000,
      location: 'Xiangshan Trail, Xinyi District, Taipei, Taiwan',
      caption: '象山から望む台北101と市街地。高層ビルの先まで住宅街が広がる、台北の都市規模が分かります。',
      photographerName: 'Lisanto 李奕良',
      photographerProfileUrl: 'https://unsplash.com/@lisanto_',
      sourceUrl: 'https://unsplash.com/photos/aerial-view-of-buildings-during-daytime-deCvIgBnPwo',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1583889659384-64d9df2347ba?auto=format&fit=crop&w=1800&q=82',
        alt: '屋台と人通りでにぎわう台北の饒河街観光夜市',
        width: 3648,
        height: 2432,
        location: 'Taipei, Taiwan',
        caption: '屋台と人通りでにぎわう饒河街観光夜市。食事や買い物を身近に楽しめる、台北の夜の日常です。',
        photographerName: 'Clement Souchet',
        photographerProfileUrl: 'https://unsplash.com/@windclems',
        sourceUrl: 'https://unsplash.com/photos/people-walking-on-street-during-night-time-gTvz-t7D1Aw',
      },
      {
        src: 'https://images.unsplash.com/photo-1591962176551-cb2d2febb7be?auto=format&fit=crop&w=1800&q=82',
        alt: '赤い提灯が並ぶ九份老街の石段と建物',
        width: 3456,
        height: 5184,
        location: 'Jiufen, Ruifang District, New Taipei City, Taiwan',
        caption: '赤い提灯と石段が続く九份老街。台北から足を延ばして楽しめる、台湾らしい街並みの一つです。',
        photographerName: 'Maren Wilczek',
        photographerProfileUrl: 'https://unsplash.com/@averagepony',
        sourceUrl: 'https://unsplash.com/photos/red-and-brown-hanging-decors-on-green-concrete-wall-during-daytime-iiSbeOl24fM',
      },
    ],
  },

  'hong-kong:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1620015092538-e33c665fc181?auto=format&fit=crop&w=2400&q=82',
      alt: '朝日に照らされたビクトリア・ハーバーと香港の高層ビル群',
      width: 4658,
      height: 3494,
      location: 'Hong Kong',
      caption: 'ビクトリア・ハーバーを挟んで広がる香港の市街地。海と山の間に高層ビルが密集する都市景観です。',
      photographerName: 'Manson',
      photographerProfileUrl: 'https://unsplash.com/@mansonyms',
      sourceUrl: 'https://unsplash.com/photos/hong-kong-skyline-across-victoria-harbour-4vf1KEkD7Gc',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1616394158624-a2ba9cfe2994?auto=format&fit=crop&w=1800&q=82',
        alt: 'ネオンとミニバスでにぎわう夜の香港・旺角',
        width: 3879,
        height: 5818,
        location: 'Mong Kok, Hong Kong',
        caption: 'ミニバスとネオンが行き交う夜の旺角。交通量や店の密度から、香港の活気ある日常を感じられます。',
        photographerName: 'Chi Hung Wong',
        photographerProfileUrl: 'https://unsplash.com/@chwong97',
        sourceUrl: 'https://unsplash.com/photos/minibuses-on-neon-street-in-mong-kok-7z_TmCWC5C0',
      },
      {
        src: 'https://images.unsplash.com/photo-1556015522-8b9b1d56d015?auto=format&fit=crop&w=1800&q=82',
        alt: '集合住宅の間を走る香港・北角の路面電車',
        width: 3944,
        height: 5916,
        location: 'North Point, Hong Kong',
        caption: '集合住宅の間を路面電車が走る北角。住まいと公共交通が近い、香港の暮らしの距離感が分かります。',
        photographerName: 'Joel Fulgencio',
        photographerProfileUrl: 'https://unsplash.com/@joelft',
        sourceUrl: 'https://unsplash.com/photos/street-with-view-of-apartment-complex-r5Xd-F2st9w',
      },
    ],
  },

  'chile:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1689850543263-01a52ccc6943?auto=format&fit=crop&w=2400&q=82',
      alt: '雪を頂くアンデス山脈を背景にしたサンティアゴ市街',
      width: 8116,
      height: 5413,
      location: 'Santiago, Chile',
      caption: 'アンデス山脈を背に広がるサンティアゴ。自然の大きさと首都の都市生活が隣り合うチリらしい風景です。',
      photographerName: 'Chalo Gallardo',
      photographerProfileUrl: 'https://unsplash.com/@chalogallardo',
      sourceUrl: 'https://unsplash.com/photos/a-view-of-a-city-with-mountains-in-the-background-eXL2DYVmq-0',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1490782300182-697b80ad4293?auto=format&fit=crop&w=1800&q=82',
        alt: '丘にカラフルな住宅が並ぶチリ・バルパライソ',
        width: 4816,
        height: 3016,
        location: 'Valparaíso, Chile',
        caption: 'カラフルな住宅が丘に連なる港町バルパライソ。首都サンティアゴとは異なる街の個性を楽しめます。',
        photographerName: 'Loïc Mermilliod',
        photographerProfileUrl: 'https://unsplash.com/@loacfr',
        sourceUrl: 'https://unsplash.com/photos/landscape-photography-of-blue-and-yellow-houses-H6KJ2D0LphU',
      },
      {
        src: 'https://images.unsplash.com/photo-1566275163755-bbb09bbc5a13?auto=format&fit=crop&w=1800&q=82',
        alt: '歴史的な建物が並ぶバルパライソの通りを走る路線バス',
        width: 4032,
        height: 3024,
        location: 'Serrano, Valparaíso, Chile',
        caption: '歴史的な建物の間を路線バスが走るバルパライソの通り。現地での移動と日常の街並みを想像できます。',
        photographerName: 'Tyler Gooding',
        photographerProfileUrl: 'https://unsplash.com/@tgooding',
        sourceUrl: 'https://unsplash.com/photos/yellow-and-green-709-bus-on-road-beside-white-van-z8J0DZzXYDI',
      },
    ],
  },

  'uruguay:working-holiday': {
    hero: {
      src: 'https://images.unsplash.com/photo-1667846788406-15622c02fe4d?auto=format&fit=crop&w=2400&q=82',
      alt: '水辺に沿って広がるウルグアイ・モンテビデオの市街地',
      width: 5914,
      height: 3326,
      location: 'Montevideo, Uruguay',
      caption: '水辺に沿って広がる首都モンテビデオ。市街地と開放的なウォーターフロントを一度に見渡せる風景です。',
      photographerName: 'Sebastián Velásquez',
      photographerProfileUrl: 'https://unsplash.com/@haiiku',
      sourceUrl: 'https://unsplash.com/photos/a-city-next-to-a-body-of-water-sRjAUpAIaw0',
    },
    inline: [
      {
        src: 'https://images.unsplash.com/photo-1590683696407-f75a80b4a61d?auto=format&fit=crop&w=1800&q=82',
        alt: 'ヤシの木越しに見上げるモンテビデオのサルボ宮殿',
        width: 6016,
        height: 4000,
        location: 'Montevideo, Uruguay',
        caption: 'モンテビデオ中心部のランドマーク、サルボ宮殿。歴史的な建築が身近に残る街の雰囲気を伝えます。',
        photographerName: 'Guillermo Vuljevas',
        photographerProfileUrl: 'https://unsplash.com/@vuljevas',
        sourceUrl: 'https://unsplash.com/photos/white-concrete-building-under-blue-sky-during-daytime-D_GJeAfV1xA',
      },
      {
        src: 'https://images.unsplash.com/photo-1742287622295-1669f3a84f9d?auto=format&fit=crop&w=1800&q=82',
        alt: '夕暮れのコロニア・デル・サクラメントにある屋外カフェ',
        width: 4160,
        height: 6240,
        location: 'Colonia del Sacramento, Uruguay',
        caption: '石畳の旧市街に席を並べるコロニア・デル・サクラメントの屋外カフェ。休日の穏やかな時間を想像できます。',
        photographerName: 'Tammy Taabassum',
        photographerProfileUrl: 'https://unsplash.com/@taamannae',
        sourceUrl: 'https://unsplash.com/photos/outdoor-cafe-under-a-tree-with-an-old-car-5Dio0xzXVg0',
      },
    ],
  },
} as const satisfies Readonly<Record<string, CountryPurposeVisualSet>>;
